### ISSUE TITLE
OSPO案例研究指南

### ISSUE THREAD

**Issue by zRich** [lfapac-open-source-evangelist/todogroup.org#12]
content/zh-CN/case-studies

**Comment by arnuojo** [comment]
Please help to confirm the content range of "Open Source Program Office Case Study Guidelines/OSPO案例研究指南".
Is it only   ["Open Source Program Office Case Study Guidelines"](https://todogroup.org/zh-cn/resources/guides/open-source-program-office-case-study-guidelines/)  (which is showed in the link) 
or the whole ["case studies"](https://github.com/lfapac-open-source-evangelist/todogroup.org/tree/main/content/zh-CN/case-studies) (which including 15 md documents).

**Comment by arnuojo** [comment]
Content of "OPEN SOURCE PROGRAM OFFICE CASE STUDY GUIDELINES" was named as[ todo-contribution-guidelines.md](https://github.com/lfapac-open-source-evangelist/todogroup.org/blob/main/content/en/guides/todo-contribution-guidelines.md)

Please review the Chinese translation version of "odo-contribution-guidelines.md"

[https://github.com/lfapac-open-source-evangelist/todogroup.org/pull/29](https://github.com/lfapac-open-source-evangelist/todogroup.org/pull/29)
