### ISSUE TITLE
制定开源战略

### ISSUE THREAD

**Issue by zRich** [lfapac-open-source-evangelist/todogroup.org#16]
content/zh-CN/guides/strategy.md

**Comment by arnuojo** [comment]
Please review the Chinese translation version of "strategy.md"
[](https://github.com/lfapac-open-source-evangelist/todogroup.org/pull/28)

**Comment by arnuojo** [comment]
[strategy _2024.6.5.md](https://github.com/user-attachments/files/15581744/strategy._2024.6.5.md)
modified based on node's comments
